services:
  webgateway:
    image: ${DOCKER_REGISTRY-}webgateway
    build:
      context: .
      dockerfile: Gateways/Web/WebGateway/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      tasks-management-net:
  
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Frontends/Web/Web/Dockerfile
    ports:
      - "7080:7080"
      - "7081:7081"
    networks:
      tasks-management-net:

  tasks-api:
    image: ${DOCKER_REGISTRY-}tasks.api
    build:
      context: .
      dockerfile: Services/Tasks/TasksApi/Dockerfile
    ports:
      - "5030:5030"
      - "5031:5031"
    depends_on:
      - tasks-db
    networks:
      tasks-management-net:

  users-api:
    image: ${DOCKER_REGISTRY-}users.api
    build:
      context: .
      dockerfile: Services/Users/UsersApi/Dockerfile
    ports:
      - "5280:5280"
      - "5281:5281"
    depends_on:
      - users-db
    networks:
      tasks-management-net:

  authen-api:
    image: ${DOCKER_REGISTRY-}authen.api
    build:
      context: .
      dockerfile: Services/Authentication/AuthenticationApi/Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    depends_on:
      - users-db
    networks:
      tasks-management-net:

  tasks-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 14331:1433
    volumes:
      - tasks_data:/var/opt/mssql
    networks:
      tasks-management-net:
    restart: unless-stopped

  users-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 14332:1433
    volumes:
      - users_data:/var/opt/mssql
    networks:
      tasks-management-net:
    restart: unless-stopped

  

volumes:
  users_data:
  tasks_data:

networks:
  tasks-management-net:
    driver: bridge




