services:
  tasks.api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5031;http://+:5030"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /home/app/.aspnet/https/Tasks.API.pfx
    volumes:
      - ./certs/.aspnet/https/Tasks.API.pfx:/home/app/.aspnet/https/Tasks.API.pfx:ro